# Generated by Django 4.1.7 on 2023-03-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_comment_user_product_is_available_alter_rank_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="product",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="store.category",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product",
            field=models.ManyToManyField(related_name="products", to="store.tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
